# Generated by Erlang.mk. Edit at your own risk!

src/chat_h.erl:: src/ezwebframe_mochijson2.erl; @touch $@
src/clock_h.erl:: src/ezwebframe_mochijson2.erl; @touch $@
src/interact_h.erl:: src/ezwebframe_mochijson2.erl; @touch $@

COMPILE_FIRST += ezwebframe_mochijson2
